name: Observe

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEWS_API_TOKEN: ${{ secrets.NEWS_API_TOKEN }}
      MAILGUN_API_TOKEN: ${{ secrets.MAILGUN_API_TOKEN }}
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_TO: ${{ secrets.MAILGUN_TO }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: yarn
      - run: yarn start
        env:
          NEWS_API_QUERY: apple
